# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('course_unit', models.CharField(choices=[('6', '6'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1)),
                ('course_type', models.CharField(choices=[('C', 'C'), ('E', 'E')], max_length=1)),
                ('total_score', models.PositiveIntegerField()),
                ('session', models.CharField(choices=[('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2019/2020', '2019/2020')], max_length=30)),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=30)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(blank=True, max_length=9, null=True)),
                ('department', models.CharField(blank=True, choices=[('Computer science', 'Computer science'), ('Microbiology', 'Microbiology'), ('Biochemistry', 'Biochemistry'), ('Economics', 'Economics'), ('English', 'English'), ('Sociology', 'Sociology')], max_length=30, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('Faculty of Science', 'Faculty of Science'), ('Faculty of Arts and Social Management science', 'Faculty of Arts'), ('Faculty of Law', 'Faculty of law'), ('Faculty of Health Science', 'Faculty of Health')], max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('100 level', '100 level'), ('200 level', '200 level'), ('300 level', '300 level'), ('400 level', '400 level')], max_length=20, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
